[package]
name = "may-i-pp"
version = "0.1.0"
edition = "2024"

[dependencies]
may-i-core = { path = "../core" }
colored = "3.1.1"

[dev-dependencies]
may-i-sexpr = { path = "../sexpr" }
proptest = "1"
