[package]
name = "may-i-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
may-i-shell-parser = { path = "../shell-parser" }
may-i-core = { path = "../core" }

[dev-dependencies]
may-i-config = { path = "../config" }
proptest = "1"
regex = "1"
